### ISSUE TITLE
Periods stripped off the end of multiline strings

### ISSUE THREAD

**Issue by akalsey** [Tessmore/sbd#14]
With multi line strings, when sbd splits the string, the period at the end of the line is removed.

```javascript
var text = "Four score and seven years ago our fathers brought forth on this continent, a new nation, conceived in Liberty, and dedicated to the proposition that all men are created equal.\
\
Now we are engaged in a great civil war, testing whether that nation, or any nation so conceived and so dedicated, can long endure.";
console.log(tokenizer.sentences(text));
/*
[ 'Four score and seven years ago our fathers brought forth on this continent, a new nation, conceived in Liberty, and dedicated to the proposition that all men are created equal',
  'Now we are engaged in a great civil war, testing whether that nation, or any nation so conceived and so dedicated, can long endure.' ]
*/
```

This doesn't happen if the multiple lines come from elsewhere, like reading a text file.

**Comment by Tessmore** [comment]
Hmmm, I guess it's weirdly inconsistent. Probably has to do with newlines as boundaries? There is an option to force them to break, but not sure if this also removes the periods.

```
var options = {
    "newline_boundaries" : true,
};
```

I'll check it :)

**Comment by Tessmore** [comment]
Hmm running your example it doesn't strip the period for me though.

**Comment by akalsey** [comment]
Here's a copy and paste of my test script. 

```javascript
var sbd = require('sbd');

var text = "How now brown cow.\
\
Peter Piper Picked a peck of pickled peppers. A peck of pickled peppers peter piper picked.";

var options = {};
console.log(sbd.sentences(text, options));

var options = {"newline_boundaries" : true};
console.log(sbd.sentences(text, options));
```

and here's the output. 

```
$ node examples/tmp.js
[ 'How now brown cow',
  'Peter Piper Picked a peck of pickled peppers.',
  'A peck of pickled peppers peter piper picked.' ]
[ 'How now brown cow',
  'Peter Piper Picked a peck of pickled peppers.',
  'A peck of pickled peppers peter piper picked.' ]
```

Running a slightly old version of node (7.0.0), let me update and see if it changes.

**Comment by akalsey** [comment]
Nope, still the same thing under 7.4.0.

```
AKALSEY-M-J03G:textchunk akalsey$ node -v
v7.4.0
AKALSEY-M-J03G:textchunk akalsey$ node examples/tmp.js
[ 'How now brown cow',
  'Peter Piper Picked a peck of pickled peppers.',
  'A peck of pickled peppers peter piper picked.' ]
[ 'How now brown cow',
  'Peter Piper Picked a peck of pickled peppers.',
  'A peck of pickled peppers peter piper picked.' ]
```

**Comment by akalsey** [comment]
Admittedly, it's an edge case. Multiline strings as a variable probably won't come up often. I only found this because my module [textchunk](https://github.com/akalsey/textchunk) uses sbd to find sentences and my unit tests use multiline strings. They weren't returning what I expected and debugging led me to this.

**Comment by Tessmore** [comment]
Very strange. I get the following running your example:
![image](https://cloud.githubusercontent.com/assets/1188065/21824267/db958c78-d77e-11e6-9f20-ae2f9274cd73.png)

So yeah... I don't know?

**Comment by Tessmore** [comment]
Haha, ok ye if I use it as a module it's indeed removing the periods :o but the module is same as on npm... strange strange

**Comment by Tessmore** [comment]
@akalsey I re-freshed the module on npm and it seems to be good now :)

**Comment by akalsey** [comment]
I now have sbd@1.0.12 but still see it. Not much of a worry as this is really the edgiest of edge cases. It's not affecting anything in my real usage, just some samples and tests. I can't imagine anyone's really doing a lot of multiline variables injected directly into the method.
