### ISSUE TITLE
sentences() loses extra whitespace in the middle of the sentence

### ISSUE THREAD

**Issue by nrotstan** [Tessmore/sbd#15]
This works as expected:

`sbd.sentences("Hello World! Goodbye cruel world.")` produces ['"Hello World!", "Goodbye cruel world."]

But if there are multiple spaces in a row between words, they are stripped out, producing different content than was given. The following has multiple spaces between Hello and World.
<pre>sbd.sentences("Hello    World! Goodbye cruel world.")</pre> produces ['"Hello World!", "Goodbye cruel world."], losing the extra spaces even though they're not at a sentence boundary.

**Comment by Tessmore** [comment]
Hey,

I guess it should not manipulate input to make sentence detection work :-)  
... but yeah, it currently "ignores" whitespace between words. Do you want to keep the whitespaces? 

Words are split here: https://github.com/Tessmore/sbd/blob/master/lib/tokenizer.js#L61

If you need to keep the whitespaces, between words, then we also need different word splitting. This probably causes more issues :(( So if you have a nice example or reason you really need it, it's appreciated!
