### ISSUE TITLE
republish

### ISSUE THREAD

**Issue by jasonphillips** [Tessmore/sbd#19]
FYI - after last version bump (0.1.13), this doesn't seem to have been published, so the [npm version](https://www.npmjs.com/package/sbd) is still 0.1.12 and lacks in particular the `preserve_whitespace` feature.

**Comment by Tessmore** [comment]
@jasonphillips Hmm weird, I am pretty sure I did publish it (doing a `yarn add` or `npm install` does give the correct version. But will make sure I publish it again too
