### ISSUE TITLE
Does this do the same as blast.js?

### ISSUE THREAD

**Issue by pjebs** [Tessmore/sbd#20]
Does this library require any dependencies? [Blast.js](https://github.com/julianshapiro/blast) requires jquery which I am trying to avoid.

Also, does this library allow adding `span` tags around the sentence boundary like blast : http://velocityjs.org/blast/

**Comment by Tessmore** [comment]
@pjebs Hmm, I don't know what `blastJS` does (the demo seems to be down?)

**Comment by pjebs** [comment]
It seems to work for me.
