### ISSUE TITLE
Implied closing p not detected

### ISSUE THREAD

**Issue by pjebs** [Tessmore/sbd#21]
When you have `<p>dsgsadsadsdgdsg<p>sdagasdgasdgsdgsdg`, the browser places a `</p>` before the second `<p>`. These are not detected.

**Comment by Tessmore** [comment]
Hi @pjebs, 

It only does simple sentence detection, mostly regex / pattern based. It can "support" html as it will just strip out everything. I think the only thing added is that it looks for `<br>`?

Maybe it works for closing `</p>`, then in your example you could first "clean up" the html and then run it through `sbd`. I wouldn't know if the first `<p>` should actually be a `</p>` or not.
