### ISSUE TITLE
Guidance on how to wrap start and end characters.

### ISSUE THREAD

**Issue by pjebs** [Tessmore/sbd#23]
Can I get some guidance on how I can wrap the start and end character of a sentence with a span.

eg.
```
Hello my name is <strong>S</strong>imon. I am 12 years old.
```

How can I produce a result of:
```
<span class="start">H</span>ello my name is <strong>S</strong>imon<span class="end">.</span> <span class="start">I</span> am 12 years old<span class="end">.</span>
```

Similar to [blast.js](http://velocityjs.org/blast/) and maybe [parse-latin](https://github.com/wooorm/parse-latin).

I tried using regex to look for your sentences and traverse the dom myself. The problem is that your library converts muliple whitespaces to a single whitespaces making regex hard.

**Comment by pjebs** [comment]
My javascript skills are not good enough to even work out where to begin when I look at your code.

**Comment by Tessmore** [comment]
@pjebs While definitely not ideal:

```
        const entry = "Hello my name is <strong>S</strong>imon. I am 12 years old.";
        const sentences = tokenizer.sentences(entry);

        const start = "";
        const ending = "</span>";

        const wrapped = [];

        for (const s of sentences) {
            const wrapStart = `<span class='start'>${s[0]}</span>`;
            const wrapEnd = `<span class='ending'>${s[s.length - 1]}</span>`;

            const newSentence = `${wrapStart}${s.substring(1, s.length - 1)}${wrapEnd}`

            wrapped.push(newSentence);
        }

        console.log(wrapped)
```

Will result in:

```
[ '<span class=\'start\'>H</span>ello my name is <strong>S</strong>imon<span class=\'ending\'>.</span>',
  '<span class=\'start\'>I</span> am 12 years old<span class=\'ending\'>.</span>' ]
```

But too be fair, this lib. isn't really built for text manipulation, so I dunno.
