### ISSUE TITLE
Cyrillic abbreviations 

### ISSUE THREAD

**Issue by InfSpell** [Tessmore/sbd#24]
Hello, if I read the code correctly, then inputting abbreviations for Cyrillic does not make sense? Or am I offended and doing something wrong?
```
const tokenizer = require('sbd');

const options = {
    "newline_boundaries" : true,
    "html_boundaries"    : false,
    "sanitize"           : false,
    "allowed_tags"       : false,
    "preserve_whitespace" : true,
    "abbreviations"      : ["табл", "рис"]
};
const text = "матрицю SWOT- аналізу (табл. 5.6). Факторами макросередовища (рис. 5.8).";
const sentences = tokenizer.sentences(text, options);

console.log(sentences)
```
```
[ 'матрицю SWOT- аналізу (табл.',
  '5.6). Факторами макросередовища (рис.',
  '5.8).' ]
```

**Comment by Tessmore** [comment]
Hi @InfSpell,

I'm sorry Cyrillic abbreviations do not seem to work. I created a patch... for that. 

Different problem is that `(табл. 5.6). Факторами` - the `5.6).` part is seen as a list enumerator, for example if you had:

```
1. Introduction
2. Content
3. Conclusion
```

So yeah, it will still not really fix your problem sorry

**Comment by InfSpell** [comment]
Thank you for your time.
