### ISSUE TITLE
Client side browser

### ISSUE THREAD

**Issue by lightningjo1997** [Tessmore/sbd#27]
Is it possible to use this library in browser and embed using script tag and cdn? 

New to programming and GitHub so not sure if this is possible

**Comment by Tessmore** [comment]
Hi,

Yes it's possible to use this library in the browser. For example, the demo uses it: http://tessmore.github.io/sbd/

The demo is very old and uses angularJS, but an example can be seen here: https://github.com/Tessmore/sbd/blob/gh-pages/index.html

```
 <script src="dist/sbd.js"></script>

<script>
  var sentences = tokenizer.sentences("hello world");
</script>
```

**Comment by lightningjo1997** [comment]
thanks so much, really helpful library!
