### ISSUE TITLE
demo page

### ISSUE THREAD

**Issue by fpereira1** [Tessmore/sbd#3]
Hi,

I just published a demo page on my fork and wanted to open a PR. But I think that because you don't have the `gh-pages` branch it isn't accepted. The demo is http://fpereira1.github.io/sbd/ - is that something you'd like to see merged?

**Comment by Tessmore** [comment]
Oh hey,  @fpereira1 I missed this one completely :o  

I opened a `gh-pages` branch now, so if you still want to create a PR I'll gladly accept it.

**Comment by fpereira1** [comment]
@Tessmore ok awesome I will see If I still have the fork somewhere :S

**Comment by Tessmore** [comment]
Cool :D

**Comment by fpereira1** [comment]
@Tessmore PR opened.  #6
