### ISSUE TITLE
Crashes on inputs that don't contain a space character

### ISSUE THREAD

**Issue by feross** [Tessmore/sbd#4]
This module assumes that the input string will always contain a space. When it does not, the module crashes on this line: https://github.com/Tessmore/sbd/blob/master/lib/tokenizer.js#L39

**Comment by Tessmore** [comment]
Do you mean if the input is undefined?

I added a test case for it now.
```
var sentences = tokenizer.sentences();
```

**Comment by feross** [comment]
It looks like the issue is fixed now. Thanks.
