### ISSUE TITLE
 quotation marks problem

### ISSUE THREAD

**Issue by mehmetilker** [Tessmore/sbd#7]
There are 2 sentence in this example but it return only one. I guess it is because  quotation marks.
Is there a easy way to handle the problem ?

“If there’s no balance and your boss doesn’t provide support and work that’s meaningful, your chances of burning out are great.” What bothers most people in situations like these is “the lack of boundaries,” says Nancy Rothbard, the David Pottruck Professor of Management at the University of Pennsylvania’s Wharton School.

**Comment by Tessmore** [comment]
Hmm, I'll look into it.

**Comment by mehmetilker** [comment]
Thank you for your work.

But how can I use last version ? 
Only lib/tokenizer.js looks updated. I am using dist/sbd.min.js.

**Comment by Tessmore** [comment]
Oh sorry! Updated the dist/sbd.js and dist/sbd.min.js now!
