### ISSUE TITLE
br tag as determiner

### ISSUE THREAD

**Issue by mehmetilker** [Tessmore/sbd#8]
`<br/>` tag should be as determiner for sentence boundary if I am not wrong ?

Is is possible to configure tokenizer to take in account `<br>` tag ?

Or even better handle a situation like this:
`
<p><strong>What the Experts Say<br /></strong>In certain circumstances, “working for a manager who’s task-oriented and has a high need for achievement can be motivating,” says Linda Hill, professor at Harvard Business School and coauthor of <a href="https://hbr.org/product/being-the-boss-the-3-imperatives-for-becoming-a-gr/an/12285-HBK-ENG"><em>Being the Boss</em></a>. But if that high-achieving manager is also an office-obsessed, iPhone-attached workaholic, it can be quite the opposite. “If there’s no balance and your <a href="https://hbr.org/2015/06/get-what-you-need-from-your-hands-off-boss">boss doesn’t provide support</a> and work that’s meaningful, your chances of <a href="https://hbr.org/2015/04/how-to-overcome-burnout-and-stay-motivated">burning out</a> are great.” What bothers most people in situations like these is “the lack of boundaries,” says <a href="https://hbr.org/search?term=nancy+rothbard">Nancy Rothbard</a>, the David Pottruck Professor of Management at the University of Pennsylvania’s Wharton School. When you report to a compulsive workaholic, suddenly, “work expands into every part of your life and it’s extremely stressful.” Whether your boss is piling on too many tasks, wants constant face time, or has unreasonable expectations about 24/7 responsiveness (or all of the above), here are some tips on how to cope.</p>`

**Comment by Tessmore** [comment]
But you want to keep html in tact?

**Comment by mehmetilker** [comment]
First and important problem is br tag, like here

`What the Experts Say <br />In certain circumstances, “working for a manager who’s task-oriented and has a high need for achievement can be motivating,” says Linda Hill`

There should be 2 sentence but I got 1.

Another problem, yes, if possible, getting sentences without changing original html... Now I am removing strong, a, em etc... tags...

**Comment by Tessmore** [comment]
Hmm, ye I'll look into it, shouldn't be too hard if it is just for <br> tags.

**Comment by Tessmore** [comment]
Ok, for your usecase:

```
var entry = "What the Experts Say <br />In certain circumstances, “working for a manager who’s task-oriented and has a high need for achievement can be motivating,” says Linda Hill";

var sentences = tokenizer.sentences(entry, { sanitize: false, "html_boundaries": true });
```

Then it will keep all html tags intact, but force breaking sentences on <br /> (and </p>, </div>).

**Comment by mehmetilker** [comment]
Perfect, I appreciate your effort. Thank you again.

I will try it after you update distribution.

One case I still have problem with the quotation mark as follow: 
(it works in simple scenarios like :
“The fear is that your manager will think you’re lazy, not committed, or less engaged,” says Hill.  )

If your boss assumes he can interrupt you any time and it’s "impacting the way you do your job," you should communicate that "you feel stretched," says Hill. A growing body of research shows that being “always on” hurts results.

**Comment by mehmetilker** [comment]
I tried your solution for html boundaries but I got this as a result.:
Talk to your bossEven when you have a grasp of the precise problem along with clear solutions, it’s still not easy to broach the subject with your boss.

I assume it should keep br tag between "boss" and "Even"
 so I can get 2 sentence.

**Comment by Tessmore** [comment]
You have { sanitize: false } right?

**Comment by mehmetilker** [comment]
Yes, and "html_boundaries": true

**Comment by Tessmore** [comment]
Can you provide the sentence you used?

**Comment by mehmetilker** [comment]
`Talk to your boss<br />Even when you have a grasp of the precise problem along with clear solutions, it’s still not easy to broach the subject with your boss.`

**Comment by Tessmore** [comment]
Hmm..

```

var entry = `Talk to your boss<br />Even when you have a grasp of the precise problem along with clear solutions, it’s still not easy to broach the subject with your boss.`
var sentences = tokenizer.sentences(entry, { "html_boundaries": true });

console.log(sentences);
```

Gives me: 
```
[ 'Talk to your boss<br />',
  'Even when you have a grasp of the precise problem along with clear solutions, it’s still not easy to broach the subject with your boss.' ]
```

So it keeps the <br /> ?

**Comment by mehmetilker** [comment]
Sorry my mistake. I was getting innerText.

It keeps br tag but still give one sentence.

What I am doing actually tagging sentences as follow;

` $(this).html(                
                tokenizer.sentences(paragraph, options).map(
                    function (v) { return '<span class="sentence">' + v + ' </span> '; }
                )
            );`

And what I get with configuration `{ "html_boundaries": true }`

![capture](https://cloud.githubusercontent.com/assets/279289/14364406/6ca159b6-fd11-11e5-97ff-4ecceaf003f7.PNG)

**Comment by Tessmore** [comment]
Ok, I'll look into that other thing too... but yeah don't expect too much. It is really difficult to split sentences correctly if the final word is a name or abbreviation.

**Comment by mehmetilker** [comment]
Yes, a problem hard to solve...
But I wondered why it did not work for me... In your example it shows 2 sentences...
br tag is in first one as it should be...

**Comment by Tessmore** [comment]
Haha ye I committed too early, I'll add changes in a few minutes

**Comment by Tessmore** [comment]
I updated it for more forms of br tag. Can you check again?

**Comment by mehmetilker** [comment]
Yes it works now for br...
But somehow it put there extra strong tag.
`<strong></strong>`



![image](https://cloud.githubusercontent.com/assets/279289/14365618/6e697c28-fd17-11e5-90b0-7f3c8245e551.png)
