### ISSUE TITLE
improper split after 'et al.' in v1.0.6

### ISSUE THREAD

**Issue by chadkirby** [Tessmore/sbd#9]
The following string is correctly treated as one sentence in v1.0.5, but v1.0.6 splits after the 'et al.'

> Claims 1–6 and 15–26 are rejected under pre-AIA 35 USC § 103(a) as being unpatentable over Chalana et al. (US 2012/0179503) in view of Oh (US 2013/0013993).

**Comment by Tessmore** [comment]
I'll look into it :+1:

**Comment by Tessmore** [comment]
Alright, I added a test case + abbreviation for et al and etc. so it should be fixed in this version 1.0.7.

**Comment by cylee192** [comment]
@Tessmore , Thanks for developing this amazing sentence boundary detection api for us!

I've started trying out the code yesterday and notice there is one issue (and found that it might be related to the changes in this thread)

If "etc." appears at the end of sentence, sbd won't consider it as a sentence boundary.

For example, "I love apples, oranges, mango etc. I want more of it" This would be considered as one sentence. 

Maybe the next word could give some hint on whether the "etc." is the end of sentence.

**Comment by Tessmore** [comment]
> Maybe the next word could give some hint on whether the "etc." is the end of sentence.

Hmm, yeah it's a pitty. I think this is a limitation of using the "rule based" approach. I think it would work if the sentence is more like:

```
I love apples, oranges, mango, (and other fruits etc.). I want more of it
```

I guess the single capital letter does give a little hint, so maybe it can be fixed. I don't think it will be super easy :(
